CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(1000)                NOT NULL,
    requestor_id BIGINT REFERENCES users (id) NOT NULL,
    created      TIMESTAMP                    NOT NULL default now()
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)                  NOT NULL,
    description TEXT                         NOT NULL,
    owner_id    BIGINT REFERENCES users (id) NOT NULL,
    available   BOOLEAN                      NOT NULL,
    request_id  BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    item_id    BIGINT REFERENCES items (id) NOT NULL,
    booker_id  BIGINT REFERENCES users (id) NOT NULL,
    status     VARCHAR(10) CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id   BIGINT REFERENCES items (id) NOT NULL,
    author_id BIGINT REFERENCES users (id) NOT NULL,
    created   TIMESTAMP                    NOT NULL DEFAULT now(),
    comment   VARCHAR(1000)                NOT NULL
)
